"""Build searchable per-unit source and geometry review, with honest evidence labels."""
from pathlib import Path
import json,cv2,numpy as np,html,collections
from PIL import Image,ImageDraw,ImageFont
root=Path.cwd();out=root/'outputs/building-quality';review=out/'review';cards=review/'buildings';cards.mkdir(exist_ok=True)
bs=json.loads((root/'work/buildings/visibility/architecture_visibility.json').read_text())['buildings'];poses=json.loads((root/'work/buildings/visibility/poses.json').read_text());font=ImageFont.truetype('/System/Library/Fonts/STHeiti Medium.ttc',21);small=ImageFont.truetype('/System/Library/Fonts/STHeiti Medium.ttc',17)
def fit(im,size):
 im=im.copy();im.thumbnail(size,Image.Resampling.LANCZOS);canvas=Image.new('RGB',size,(42,49,53));canvas.paste(im,((size[0]-im.width)//2,(size[1]-im.height)//2));return canvas
entries=[];allcards=[]
for i,b in enumerate(bs):
 page=i//16+1;idx=i%16;p=poses[str(b['t'])];source=Image.open(root/p['source']);q=np.array(b['roof_world']);bottom=q.copy();bottom[:,2]=b['base_height'];q=np.vstack([q,bottom]);R=np.array(p['rotation']);T=np.array(p['translation']);pc=q@R.T+T;xy=pc[:,:2]/pc[:,2,None];xy=xy*(1+p['radial']*(xy*xy).sum(1))[:,None]*p['focal']+[800,450];lo=np.floor(xy.min(0)-10);hi=np.ceil(xy.max(0)+10);lo=np.maximum(lo,[0,0]);hi=np.minimum(hi,[1600,900]);scale=source.width/1600;box=tuple((np.r_[lo,hi]*scale).astype(int));source=source.crop(box);atlas=Image.open(review/f'geometry_{page:02}.png');x=(idx%4)*600;y=(idx//4)*300;model=atlas.crop((x,y,x+600,y+300));card=Image.new('RGB',(900,350),(242,241,236));card.paste(fit(source,(300,300)),(0,50));card.paste(model,(300,50));draw=ImageDraw.Draw(card);draw.text((10,4),b['id']+'  '+b['name'],font=font,fill=(30,38,40));draw.text((10,28),'视频参考 / '+str(b['t'])+' 秒',font=small,fill=(70,78,80));draw.text((315,28),'模型正面斜视',font=small,fill=(70,78,80));draw.text((615,28),'模型背面斜视',font=small,fill=(70,78,80));card.save(cards/f'{b["id"]}.jpg',quality=91);allcards.append(card);entries.append(dict(id=b['id'],name=b['name'],type=b['type'],source_seconds=b['t'],roof_point_support=b['roof_support'],parent=b.get('parent'),review_image=f'review/buildings/{b["id"]}.jpg',inferred='背面、遮挡区域、门窗及附属细节按用户授权推测；尺寸为近似值。'))
for page in range((len(allcards)+15)//16):
 canvas=Image.new('RGB',(1800,2800),(242,241,236))
 for j,card in enumerate(allcards[page*16:(page+1)*16]):canvas.paste(card,((j%2)*900,(j//2)*350))
 canvas.save(review/f'contact_{page+1:02}.jpg',quality=91)
(out/'building_inventory.json').write_text(json.dumps(entries,ensure_ascii=False,indent=2));import csv
with (out/'building_inventory.csv').open('w',newline='',encoding='utf-8-sig') as f:
 w=csv.DictWriter(f,fieldnames=['id','name','type','source_seconds','roof_point_support','parent','inferred']);w.writeheader();w.writerows([{k:b[k] for k in w.fieldnames} for b in entries])
items=''.join('<article data-search="'+html.escape(b['id']+' '+b['name']+' '+b['type'])+'"><a href="'+b['review_image']+'" target="_blank"><img loading="lazy" src="'+b['review_image']+'" alt="'+html.escape(b['name'])+'"></a><div><b>'+b['id']+' · '+html.escape(b['name'])+'</b><span>'+str(b['source_seconds'])+' 秒参考 · '+b['type']+'</span></div></article>' for b in entries)
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>XZ Village · 逐栋重建</title><style>*{box-sizing:border-box}body{margin:0;background:#171f22;color:#e6e9e5;font:16px system-ui,-apple-system,sans-serif}header,main{max-width:1450px;margin:auto;padding:36px 28px}header{border-bottom:1px solid #465357}small{color:#abbfc3;letter-spacing:3px}h1{font-size:42px;margin:14px 0}p{line-height:1.8;color:#c4d0d1;max-width:1000px}a{color:#bad8c4}nav{display:flex;gap:20px;flex-wrap:wrap;margin-top:24px}.overview{width:100%;border-radius:10px;margin-top:26px}.controls{position:sticky;top:0;background:#171f22ee;padding:16px 0;z-index:2;display:flex;align-items:center;gap:22px}input{padding:14px 16px;background:#29383d;border:1px solid #637a80;color:white;border-radius:8px;width:min(500px,70%);font-size:16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{background:#273339;border:1px solid #3c4c52;border-radius:8px;overflow:hidden}article img{display:block;width:100%}article div{padding:14px}article span{display:block;font-size:13px;color:#adc0c6;margin-top:8px}@media(max-width:850px){.grid{grid-template-columns:1fr}h1{font-size:30px}}footer{padding:35px 0;color:#a9b9bc;line-height:1.7}</style><header><small>XZ VILLAGE / ARCHITECTURAL RECONSTRUCTION</small><h1>整村建筑，逐栋可查看</h1><p>保留红框基准建筑，新增逐栋建筑模型。每张卡片左侧为视频参考，中间与右侧为同一模型的正面和背面斜视图。建筑轮廓与布局参考视频；看不清的门窗、背面、层高和附属细节按授权合理补全。编号包含连接侧翼和小型附属房，不等同于独立住户数量。</p><nav><a href="Village_Reconstructed.blend">打开 Blender 模型</a><a href="RECONSTRUCTION_REPORT.md">重建说明与校验</a><a href="building_inventory.csv">建筑清单 CSV</a><a href="Coverage_44s.jpg">视频编号覆盖图</a><a href="Geometry_Overview.png">无照片材质的结构检查</a></nav><img class="overview" src="Whole_Village.png" alt="整村模型全景"></header><main><div class="controls"><input id="search" aria-label="查找建筑" placeholder="查找编号、名称或屋顶类型"><span id="count"></span></div><div class="grid">'''+items+'''</div><footer>原始基准建筑 B001 保存在 Blender 的 01–03 TARGET 集合中。本页包含其余建筑单元的双向模型预览。道路、地形和植物为背景近似；本成果不作为测绘或施工模型。</footer></main><script>const cards=[...document.querySelectorAll('article')],q=document.querySelector('#search'),count=document.querySelector('#count');function filter(){let n=0;for(const c of cards){const show=c.dataset.search.toLowerCase().includes(q.value.trim().toLowerCase());c.hidden=!show;if(show)n++}count.textContent=n+' 个建筑单元'}q.addEventListener('input',filter);filter();</script></html>'''
(out/'Village_Review.html').write_text(page);print('Packaged',len(entries),'dual-view cards and',len(allcards)//16+1,'review pages')
