from pathlib import Path
import shutil,json,html
from PIL import Image,ImageDraw,ImageFont
P=Path('work/rebuild4/architecture');O=Path('/Users/zenghang/Documents/Codex/2026-09-12/jie/outputs/XZ-Village-Rebuilt-V4');cards=[]
for sec,label in [(44,'临路街区与主池塘'),(256,'返程方向的密集老屋'),(0,'南侧住宅'),(64,'池塘与通村道路'),(80,'公共楼与北端街区'),(90,'北侧住宅组'),(120,'山坡道路与住宅')]:
 source=Image.open(f'work/rebuild4/village_surface/images/frame_{sec:03}.00.jpg').convert('RGB');model=Image.open(P/f'village_detailed/detailed_{sec:03}.png').convert('RGBA');bg=Image.new('RGBA',model.size,'#d8e0db');bg.alpha_composite(model);model=bg.convert('RGB');source.thumbnail((1758,990));model=model.resize(source.size);source.save(O/'renders'/f'Source_{sec:03}.jpg',quality=94);model.save(O/'renders'/f'Model_{sec:03}.jpg',quality=94)
 pair=Image.new('RGB',(source.width*2,source.height+36),'#edf0e9');pair.paste(source,(0,36));pair.paste(model,(source.width,36));dr=ImageDraw.Draw(pair);f=ImageFont.truetype('/System/Library/Fonts/Menlo.ttc',18);dr.text((14,8),f'SOURCE {sec:03}',font=f,fill='#213830');dr.text((source.width+14,8),'V4 MODEL',font=f,fill='#213830');pair.save(O/'renders'/f'Comparison_{sec:03}.jpg',quality=93)
 cards.append(f'<section class="compare" id="frame{sec}"><h2>{sec} 秒 · {label}</h2><div class="pair"><figure><img src="renders/Source_{sec:03}.jpg" alt="{label}原片"><figcaption>原视频画面（按相机模型去畸变）</figcaption></figure><figure><img src="renders/Model_{sec:03}.jpg" alt="{label}重建模型"><figcaption>相同机位的纯几何模型渲染</figcaption></figure></div><details><summary>展开透明叠加检查</summary><label>模型透明度 <input class="opacity" type="range" min="0" max="100" value="50"></label><div class="overlay"><img src="renders/Source_{sec:03}.jpg"><img class="top" src="renders/Model_{sec:03}.jpg" style="opacity:.5"></div></details><p class="links"><a href="evidence/Roof_Identifiers_{sec:03}.jpg">打开该机位的建筑编号与檐口轮廓图</a> · <a href="renders/Comparison_{sec:03}.jpg">下载并排对照图</a></p></section>')
extra='<style>details{padding:18px 22px}summary{cursor:pointer;color:#366647}details label{display:flex;align-items:center;gap:20px;margin:16px 0}.overlay{position:relative}.overlay img{display:block;width:100%}.overlay .top{position:absolute;inset:0}input[type=range]{width:240px;padding:0}.links{padding:0 22px 18px;font-size:13px;line-height:1.8}</style>'
(O/'Source_Comparison.html').write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>原片机位对照 · 曾村重建 V4</title><link rel="stylesheet" href="style.css">'+extra+'<header><h1>从原视频机位检查整村模型</h1><p>这组图直接比较同一相机位置下的原片与模型，用来检查覆盖、体量、间距和遮挡。原片没有贴进模型；远景、植被和被遮挡的建筑细部仍存在简化。</p><nav><a href="Village_Viewer.html">三维模型</a><a href="Building_Catalogue.html">逐栋图册</a><a href="README.md">交付说明</a></nav></header><main>'+''.join(cards)+'</main><footer>编号图显示模型檐口投影，斜屋顶和屋顶设备可能高于这条轮廓。相机误差较低不能证明建筑无遗漏或外观完全一致。</footer><script>document.querySelectorAll(".opacity").forEach(x=>x.oninput=()=>x.closest("details").querySelector(".top").style.opacity=x.value/100)</script></html>')
for src in (P/'final_gallery').glob('geometry_*.jpg'):shutil.copy2(src,O/'gallery'/src.name)
shutil.copy2(P/'final_gallery/gallery_manifest.json',O/'evidence/gallery_manifest.json')
shutil.copy2(P/'static_geometry_audit.json',O/'evidence/static_geometry_audit.json')
shutil.copy2(P/'village_detailed/build_ledger.json',O/'evidence/build_ledger.json')
shutil.copy2(P/'web/web_geometry_ledger.json',O/'evidence/web_geometry_ledger.json')
shutil.copy2(P/'village_detailed/architecture.blend',O/'Village_Rebuilt_Master.blend')
print('COMPARISON_AND_MASTER_DELIVERED',len(cards))
