"""Create native-video references and navigable, source-linked building catalogue."""
from pathlib import Path
import json,html,numpy as np,shutil
from PIL import Image,ImageDraw,ImageFont
from rebuild_v4_arch_geometry import project
P=Path('work/rebuild4/architecture');OUT=Path('/Users/zenghang/Documents/Codex/2026-09-12/jie/outputs/XZ-Village-Rebuilt-V4');OUT.mkdir(parents=True,exist_ok=True)
for sub in ['references','gallery','evidence','renders','data']:(OUT/sub).mkdir(exist_ok=True)
d=json.loads((P/'village_mesh_input.json').read_text());profiles={p['id']:p for p in json.loads((P/'village_profiles.json').read_text())['entries']};cache={};metadata=[];cards=[]
types={'flat':'平屋顶','gable':'双坡瓦屋顶','metal':'金属屋面','hip':'四坡屋顶','solar':'光伏顶棚','hip_metal':'双坡金属屋顶'}
for i,b in enumerate(d['entries']):
 name=b.get('source_image','frame_044.00.jpg');src=Path('work/rebuild4/sfm/images')/name
 if not src.exists():name='frame_044.00.jpg';src=Path('work/rebuild4/sfm/images')/name
 if name not in cache:cache[name]=Image.open(src).convert('RGB')
 im=cache[name];xy=np.array(b['footprint_world']);vertices=np.vstack([np.c_[xy,np.full(len(xy),z)] for z in [b['base_height'],b['roof_edge_height']+min(2,b.get('ridge_height',b['roof_edge_height'])-b['roof_edge_height'])]]);uv=project(vertices,name);lo=np.maximum(0,np.floor(uv.min(0)-24)).astype(int);hi=np.minimum(im.size,np.ceil(uv.max(0)+24)).astype(int)
 if np.any(hi<=lo):lo=np.array([0,0]);hi=np.array(im.size)
 crop=im.crop((*lo,*hi));crop.thumbnail((720,560));crop.save(OUT/'references'/f'{b["id"]}.jpg',quality=92)
 role=b.get('source_role');label='光伏顶棚' if b['roof_type']=='solar' else ('雨棚' if role=='canopy' else ('传统厅堂' if b.get('special_model')=='curved_ridge_hall' else ('临水舞台' if b.get('special_model')=='open_stage' else ('公共楼' if b['id']=='V0490' else types.get(b['roof_type'],'建筑单元')))))
 entry=dict(id=b['id'],label=label,type_label=types.get(b['roof_type'],b['roof_type']),floor_count=b['floor_count'],view_camera='source_'+name[6:9],reference=f'references/{b["id"]}.jpg',reference_label=f'原视频 {name[6:12]} 秒局部 · 画面内可能包含邻栋',source_ids=b.get('source_ids',[b['id']]),bounds=[vertices.min(0).tolist(),vertices.max(0).tolist()]);metadata.append(entry)
 page=i//16+1;cell=i%16;cards.append(f'<article id="{b["id"]}" data-search="{b["id"].lower()} {label}"><div class="cardhead"><b>{b["id"]}</b><span>{label}</span></div><a href="Village_Viewer.html#{b["id"]}"><div class="modelcrop" style="background-image:url(gallery/geometry_{page:02}.jpg);background-position:{cell%4*100/3:.4f}% {cell//4*100/3:.4f}%"></div></a><img loading="lazy" src="{entry["reference"]}" alt="{b["id"]} 原片局部"><p>{entry["reference_label"]}</p><a class="button" href="Village_Viewer.html#{b["id"]}">在三维模型中查看</a></article>')
(OUT/'data/viewer_metadata.json').write_text(json.dumps(dict(entries=metadata,cameras=d['cameras']),ensure_ascii=False))
style='''*{box-sizing:border-box}body{margin:0;background:#edf0ec;color:#243530;font:15px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}header{padding:30px 4vw 22px;background:#193d34;color:white}h1{font-size:28px;margin:0 0 12px}header p{max-width:900px;line-height:1.7;color:#d1e3d9;margin:8px 0}nav{display:flex;gap:18px;margin:16px 0 0}nav a{color:#f9c98b;text-decoration:none}main{padding:24px 4vw}a{color:#21634d}input{width:min(480px,100%);padding:13px;border:1px solid #9daf9f;border-radius:6px;font:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px;margin-top:22px}article{background:#fff;border:1px solid #d5ddd6;border-radius:9px;overflow:hidden;scroll-margin-top:15px;box-shadow:0 3px 14px #2537300a}.cardhead{padding:13px 16px;display:flex;justify-content:space-between}.modelcrop{aspect-ratio:2;background-size:400% 400%;background-repeat:no-repeat}article img{width:100%;height:225px;object-fit:contain;background:#dce1dc}article p{padding:0 16px;font-size:12px;color:#607568}.button{display:block;padding:12px 16px;background:#f1f6ee;font-size:13px;text-decoration:none}footer{padding:28px 4vw;color:#607568;font-size:13px}.compare{background:white;border-radius:8px;overflow:hidden;margin:26px 0}.compare h2{padding:18px;margin:0;font-size:19px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:2px;background:#e3e8e0}.pair img{width:100%;display:block}.pair figure{margin:0}.pair figcaption{padding:10px 15px;font-size:13px}.overview img{width:100%}@media(max-width:700px){.pair{grid-template-columns:1fr}}'''
(OUT/'style.css').write_text(style)
(OUT/'Building_Catalogue.html').write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>逐栋图册 · 曾村重建 V4</title><link rel="stylesheet" href="style.css"><header><h1>逐栋模型与原片参考</h1><p>402 个建筑及附属单元。每张模型卡展示相反的两个方向，下方是该单元在原视频中的局部画面。编号包含主体、侧翼和顶棚，不能直接作为独立住宅数量。</p><nav><a href="Village_Viewer.html">三维模型</a><a href="Source_Comparison.html">原片机位对照</a><a href="README.md">交付说明</a></nav></header><main><input id="filter" placeholder="输入编号或屋顶类型，如 V0329、瓦屋顶"><div class="grid">'+''.join(cards)+'</div></main><footer>原片图片仅用作对照；模型采用独立几何与程序材质。被遮挡的细部保留简化或推断。</footer><script>document.getElementById("filter").oninput=e=>{let q=e.target.value.toLowerCase().trim();document.querySelectorAll("article").forEach(x=>x.hidden=!x.dataset.search.includes(q))};</script></html>')
print('PREPARED',len(metadata),'REFERENCES',OUT)
